### ISSUE TITLE
Exception while creating the OpenGL context

### ISSUE THREAD

**Issue by Alvarito050506** [BrickBench/BrickBench#15]
Hello! So, I'm getting some OpenGL/OpenGG exception when trying to run BrickBench. Apparently OpenGG isn't able to create the OpenGL context and then the entire program silently fails, without "crashing" or destroying the windows. I'm actually not sure if it is an OpenGG issue or just a bug in the program, so I will report it here to start.

I'm using BrickBench `v0.2.1`, and the following is all the information provided by the program.

### System Information
 + Operating System: Windows 10
 + OS Architecture: amd64
 + Processor: Intel64 Family 6 Model 55 Stepping 3, GenuineIntel
 + CPU Count: 2

### Java Information
 + Java Version: 15
 + JVM Name: OpenJDK 64-Bit Server VM
 + JVM Vendor: AdoptOpenJDK
 + Maximum Runtime Memory: 1042284544
 + Used Runtime Memory: 67108864
 + Free Runtime Memory: 51717880
 + JVM CPU Availability: 2

### [OpenGG?] Engine Information
[Blank]

### OpenGL Information
[Blank]

### Complete logs
```
INFO (OpenGG): OpenGG initializing, running on Windows 10, amd64
INFO (OpenGG): Initializing application CSC Loader with app ID -1
INFO (OpenGG): Switched runtime security to OpenGG security policy
INFO (Resource): Initializing resource system in D:\Downloads\BrickBench
INFO (ResourceLoader): Initializing parallel resource loader with 8 worker thread(s)
INFO (OpenGG): Resource system initialized
INFO (OpenGG): Loaded configuration files
INFO (WindowTypeRegister): Registered a window type named GLFW
INFO (WindowTypeRegister): Registered a window type named OpenVR
INFO (WindowTypeRegister): Registered a window type named AWT
INFO (WindowController): Window registered under the name AWT requested and found, creating instance...
ERROR (OpenGG): Uncaught exception: Exception while creating the OpenGL context
java.lang.RuntimeException: Exception while creating the OpenGL context
        at com.opengg.core/com.opengg.core.render.window.awt.window.AWTGLCanvas.beforeRender(Unknown Source)
        at com.opengg.core/com.opengg.core.render.window.awt.window.GGCanvas.startFrame(Unknown Source)
        at com.opengg.core/com.opengg.core.render.window.awt.window.GGCanvas.setup(Unknown Source)
        at com.opengg.core/com.opengg.core.render.window.WindowController.setup(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.initializeClient(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.initializeLocal(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.initialize(Unknown Source)
        at com.opengg.loader/com.opengg.loader.MapViewer.main(Unknown Source)
Caused by: java.awt.AWTException: Failed to create OpenGL context.
        at com.opengg.core/com.opengg.core.render.window.awt.window.PlatformWin32GLCanvas.create(Unknown Source)
        at com.opengg.core/com.opengg.core.render.window.awt.window.PlatformWin32GLCanvas.create(Unknown Source)
        ... 8 more
INFO (OpenGG): OpenGG Engine Version: 0.1

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.opengg.core.render.Renderer.destroy()" because "com.opengg.core.render.RenderEngine.renderer" is null
        at com.opengg.core/com.opengg.core.render.RenderEngine.destroy(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.closeEngine(Unknown Source)
        at com.opengg.core/com.opengg.core.engine.OpenGG.initialize(Unknown Source)
        at com.opengg.loader/com.opengg.loader.MapViewer.main(Unknown Source)
```

**Comment by javster101** [comment]
Do you know what graphics card your computer uses? This may be an OpenGL version issue.

**Comment by Alvarito050506** [comment]
To be honest, I don't, and I don't think I can find it out easily, so I'll try in a different computer and report what happens.

**Comment by Alvarito050506** [comment]
Ok, confirmed, it was just the graphics card/software that is probably outdated. Sorry.
