### ISSUE TITLE
BrickBench v0.3.1 not working

### ISSUE THREAD

**Issue by KonstantinMashura** [BrickBench/BrickBench#46]
BrickBench v0.3.1 can't be opened properly. Instead, it's only showing me this logo while I can see the program opened in that small window over the taskbar.

Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
RAM: 8.00 GB (7.70 GB available)
Windows 7, 64bit

![issue](https://user-images.githubusercontent.com/47869403/152657731-60395f9f-0f9c-4a02-af67-9621b8f2a722.jpg)

**Comment by KonstantinMashura** [comment]
Ok, now I managed to open it but it's showing so many errors and I don't have "Create project" and "Load map/project" buttons here
![image](https://user-images.githubusercontent.com/47869403/152675697-560e8b86-552c-4124-b795-09a63d74de7f.png)

**Comment by KonstantinMashura** [comment]
After I closed the Objects tool, disabled the full-screen mode, the bar with File, View, Tools, Import, Help magically appeared but it doesn't help much because when I try to load a map, following documentation.pdf, absolutely nothing happens. Nothing is loading.
![image](https://user-images.githubusercontent.com/47869403/152861402-fbca7b07-274d-486b-8a89-32265e22ad67.png)

**Comment by javster101** [comment]
Can you send a log here? You can find the logs in `Documens/BrickBench Files/log`

**Comment by KonstantinMashura** [comment]
> Can you send a log here? You can find the logs in `Documens/BrickBench Files/log`
There's no log files in that folder. I have only this info that the OpenGG Console gives

[11:52:07.581505] INFO (OpenGG): OpenGG initializing, running on Windows 7, amd64
[11:52:07.646508] INFO (OpenGG): Initializing application BrickBench with app ID -1
[11:52:07.652509] INFO (OpenGG): Switched runtime security to OpenGG security policy
[11:52:07.674510] INFO (Resource): Initializing resource system in C:\Program Files\BrickBench
[11:52:07.680510] INFO (ResourceLoader): Initializing parallel resource loader with 8 worker thread(s)
[11:52:07.690511] INFO (OpenGG): Resource system initialized
[11:52:07.741514] INFO (OpenGG): Loaded configuration files
[11:52:07.763515] INFO (WindowTypeRegister): Registered a window type named GLFW
[11:52:07.768515] INFO (WindowTypeRegister): Registered a window type named OpenVR
[11:52:07.770515] INFO (WindowTypeRegister): Registered a window type named AWT
[11:52:07.772515] INFO (WindowController): Window registered under the name AWT requested and found, creating instance...
[11:52:08.226541] ERROR (OpenGG): Uncaught exception: Exception while creating the OpenGL context
[11:52:08.230542] ERROR (GGConsole$2): java.lang.RuntimeException: Exception while creating the OpenGL context
[11:52:08.233542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.window.awt.window.AWTGLCanvas.beforeRender(Unknown Source)
[11:52:08.236542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.window.awt.window.GGCanvas.startFrame(Unknown Source)
[11:52:08.237542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.window.awt.window.GGCanvas.setup(Unknown Source)
[11:52:08.238542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.window.WindowController.setup(Unknown Source)
[11:52:08.239542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.engine.OpenGG.initializeClient(Unknown Source)
[11:52:08.240542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.engine.OpenGG.initializeLocal(Unknown Source)
[11:52:08.244542] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.engine.OpenGG.initialize(Unknown Source)
[11:52:08.245543] ERROR (GGConsole$2): 	at com.opengg.loader/com.opengg.loader.BrickBench.main(Unknown Source)
[11:52:08.246543] ERROR (GGConsole$2): Caused by: java.awt.AWTException: Failed to create OpenGL context.
[11:52:08.247543] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.window.awt.window.PlatformWin32GLCanvas.create(Unknown Source)
[11:52:08.248543] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.window.awt.window.PlatformWin32GLCanvas.create(Unknown Source)
[11:52:08.249543] ERROR (GGConsole$2): 	... 8 more
[11:52:08.264544] ERROR (GGConsole$2): java.lang.NullPointerException: Cannot invoke "com.opengg.core.render.Renderer.destroy()" because "com.opengg.core.render.RenderEngine.renderer" is null
[11:52:08.265544] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.render.RenderEngine.destroy(Unknown Source)
[11:52:08.267544] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.engine.OpenGG.closeEngine(Unknown Source)
[11:52:08.267544] ERROR (GGConsole$2): 	at com.opengg.core/com.opengg.core.engine.OpenGG.initialize(Unknown Source)
[11:52:08.273544] ERROR (GGConsole$2): 	at com.opengg.loader/com.opengg.loader.BrickBench.main(Unknown Source)


I was already told that Brickbench is not compatible with Windows 7. I hope Windows 7 support will be added someday. But now, if it's not working for me because I have Windows 7 and this issue that I created is worthless, I'd like you to delete it.

**Comment by cOcOnUtGaming** [comment]
I have 1:1 the same problem, but I have Windows 10
