### ISSUE TITLE
BrickBench.exe wont open?

### ISSUE THREAD

**Issue by Justinwest605** [BrickBench/BrickBench#54]
**Describe the bug**
I am not good with computers. I have just downloaded BrickBench and I tried to open "BrickBench.exe" and the open screen that says "BrickBench - v0.3.3 Alpha" comes up but stops and then says "BrickBench has closed abnormally. Please view the logs and report this to the developers." This might be something on my side, because my computer isn't the best.

**To Reproduce**
1. Double click "BrickBench.exe"
2. Closed.

**Expected behavior**
I thought it was going to show the window that is seen in the instructions.

**Logs**
[22:21:37.937352] INFO (OpenGG): OpenGG initializing, running on Windows 10, amd64
[22:21:37.974328] INFO (OpenGG): Initializing application BrickBench with app ID -1
[22:21:37.979324] INFO (OpenGG): Switched runtime security to OpenGG security policy
[22:21:37.981324] INFO (Resource): Initializing resource system in C:\Program Files\BrickBench
[22:21:37.986323] INFO (ResourceLoader): Initializing parallel resource loader with 8 worker thread(s)
[22:21:37.993316] INFO (OpenGG): Resource system initialized
[22:21:38.002311] INFO (OpenGG): Loaded configuration files
[22:21:38.010305] INFO (WindowTypeRegister): Registered a window type named GLFW
[22:21:38.013304] INFO (WindowTypeRegister): Registered a window type named OpenVR
[22:21:38.015304] INFO (WindowTypeRegister): Registered a window type named AWT
[22:21:38.017303] INFO (WindowController): Window registered under the name AWT requested and found, creating instance...
[22:21:38.201186] ERROR (OpenGG): Exception while creating the OpenGL context at java.lang.RuntimeException: Exception while creating the OpenGL context
	at com.opengg.core/com.opengg.core.render.window.awt.window.AWTGLCanvas.beforeRender(Unknown Source)
	at com.opengg.core/com.opengg.core.render.window.awt.window.GGCanvas.startFrame(Unknown Source)
	at com.opengg.core/com.opengg.core.render.window.awt.window.GGCanvas.setup(Unknown Source)
	at com.opengg.core/com.opengg.core.render.window.WindowController.setup(Unknown Source)
	at com.opengg.core/com.opengg.core.engine.OpenGG.initializeClient(Unknown Source)
	at com.opengg.core/com.opengg.core.engine.OpenGG.initializeLocal(Unknown Source)
	at com.opengg.core/com.opengg.core.engine.OpenGG.initialize(Unknown Source)
	at com.opengg.loader/com.opengg.loader.BrickBench.main(Unknown Source)
Caused by: java.awt.AWTException: Failed to create OpenGL context.
	at com.opengg.core/com.opengg.core.render.window.awt.window.PlatformWin32GLCanvas.create(Unknown Source)
	at com.opengg.core/com.opengg.core.render.window.awt.window.PlatformWin32GLCanvas.create(Unknown Source)
	... 8 more

**Additional context**
Java Version: 18.0.2
JVM Name: OpenJDK 64-Bit Server VM
JVM Vendor: Azul Systems, Inc.
Maximum Runtime Memory: 4261412864
Used Runtime Memory: 29360128
Free Runtime Memory: 17286288
JVM CPU Availability: 8

**Comment by Justinwest605** [comment]
don't have enough iGPU.
